window.NORTHSTAR_STARTER_DATA = {
  decisions: [
    {
      id: "financial-direction",
      title: "Choose the strategic financial model and funding direction",
      agenda: "Pro Forma & Funding",
      project: "Veteran Ready Operating Model",
      okr: "KR2 — Unit cost validated",
      status: "decision",
      priority: "High",
      decisionMade: "Pending the September 4 operations meeting",
      evidence: ["Shared platform and IP allocation", "Employer revenue timing", "Foundation funding restrictions"],
      owner: "Finance lead",
      due: "2026-09-11",
      gate: "Approve base, upside, and downside model",
      progress: 35,
    },
    {
      id: "unit-cost-method",
      title: "Agree on one unit-cost method across CR, VR, and BUS",
      agenda: "Pro Forma & Funding",
      project: "Veteran Ready Operating Model",
      okr: "KR2 — Unit cost validated",
      status: "evidence",
      priority: "High",
      decisionMade: "Pending. Proposed measure: fully loaded cost per enrolled participant and per successful completion",
      evidence: ["Delivery labor by role", "Shared platform allocation", "Recruiting cost by channel"],
      owner: "CR and BUS finance owners",
      due: "2026-09-11",
      gate: "Unit-cost working session",
      progress: 45,
    },
    {
      id: "hampton-standard",
      title: "Adopt, revise, or hold the Hampton Roads evidence standard",
      agenda: "Hampton Roads Standard",
      project: "Hampton Roads Market Validation",
      okr: "KR1 — Employer evidence complete",
      status: "evidence",
      priority: "High",
      decisionMade: "Pending the September 4 operations meeting",
      evidence: ["Named employers with verified demand", "Recruiting funnel by source", "Minimum viable cohort size"],
      owner: "Recruiting lead",
      due: "2026-09-10",
      gate: "Pilot-readiness review",
      progress: 58,
    },
    {
      id: "business-agent-pilot",
      title: "Go, revise, or hold on a bounded Business Agent pilot",
      agenda: "Business Agent",
      project: "Business Agent Pilot",
      okr: "KR3 — Launch gates owned",
      status: "decision",
      priority: "High",
      decisionMade: "Pending receipt of the pilot terms from Peter",
      evidence: ["Written scope and cost", "Security and data boundaries", "Support, ownership, and exit terms", "Named team capacity"],
      owner: "Peter",
      due: "2026-09-08",
      gate: "Go, revise, or hold review",
      progress: 30,
    },
    {
      id: "website-soft-launch",
      title: "Confirm the Veteran Ready soft-launch gate",
      agenda: "Veteran Ready Website",
      project: "Veteran Ready Digital Launch",
      okr: "KR3 — Launch gates owned",
      status: "in_progress",
      priority: "Medium",
      decisionMade: "Pending. Working direction: controlled soft launch after every release gate has a named owner",
      evidence: ["Final offer and CTA", "Proof points", "Privacy and legal review", "Working contact path"],
      owner: "Website lead",
      due: "2026-09-15",
      gate: "Soft-launch readiness review",
      progress: 62,
    },
    {
      id: "file-system",
      title: "Confirm the canonical CR/VR file location",
      agenda: "CR/VR File System",
      project: "CR/VR Knowledge System",
      okr: "KR2 — Migration verified",
      status: "decision",
      priority: "Medium",
      decisionMade: "Pending choice between Google Drive and Teams as the authoritative record",
      evidence: ["Platform choice", "Access-owner list", "Current-file inventory"],
      owner: "Operations lead",
      due: "2026-09-09",
      gate: "Migration cutover approval",
      progress: 25,
    },
    {
      id: "file-taxonomy",
      title: "Approve taxonomy, naming, and version rules",
      agenda: "CR/VR File System",
      project: "CR/VR Knowledge System",
      okr: "KR2 — Migration verified",
      status: "in_progress",
      priority: "Medium",
      decisionMade: "Starter proposal: one numbered top-level taxonomy, named document owners, and date-based version labels",
      evidence: ["Team review of the starter taxonomy"],
      owner: "Eddie",
      due: "2026-09-12",
      gate: "Taxonomy sign-off",
      progress: 55,
    },
  ],
  objectives: [
    {
      id: "pilot-ready",
      name: "Pilot-ready operating model",
      timeframe: "Q3 2026",
      owner: "CR/VR operating team",
      why: "Prove that one market can recruit, deliver, measure, and fund a cohort in a repeatable way.",
      krs: [
        { name: "Employer evidence complete", progress: 58 },
        { name: "Unit cost validated", progress: 45 },
        { name: "Launch gates owned", progress: 62 },
      ],
    },
    {
      id: "repeatable-system",
      name: "Clear and repeatable operating system",
      timeframe: "Q3 2026",
      owner: "Eddie and Ops",
      why: "Give the team one place to see decisions, owners, evidence, deadlines, and the next gate.",
      krs: [
        { name: "Every agenda area has one owner", progress: 80 },
        { name: "File migration verified", progress: 25 },
        { name: "Weekly decision register used", progress: 50 },
      ],
    },
    {
      id: "employer-proof",
      name: "Proof that employers will participate",
      timeframe: "Pilot gate",
      owner: "CR and BUS recruiting",
      why: "Test real employer demand and the recruiting process before the team commits to a full pilot.",
      krs: [
        { name: "Qualified employer conversations", progress: 40 },
        { name: "Role demand documented", progress: 35 },
        { name: "Recruiting funnel baseline", progress: 55 },
      ],
    },
  ],
  projects: [
    {
      name: "Veteran Ready Operating System",
      category: "Operations leadership",
      challenge: "Five important workstreams needed decisions in one 60-minute meeting.",
      response: "Built one agenda clock and a decision record that forces every topic to leave with an owner or a missing fact.",
      gate: "September 4 operating review",
      metric: "5 workstreams, 1 shared decision format",
    },
    {
      name: "Hampton Roads Market Validation",
      category: "Go-to-market operations",
      challenge: "The team needed a consistent standard for deciding whether a market is ready for a pilot.",
      response: "Connected employer proof, recruiting evidence, delivery ownership, and unit economics to one readiness gate.",
      gate: "Pilot-readiness evidence",
      metric: "Employer demand, funnel, and cohort cost",
    },
    {
      name: "Business Agent Bounded Pilot",
      category: "Product and risk",
      challenge: "A small internal use case risked becoming an open-ended platform commitment.",
      response: "Separated the internal test from the larger platform decision and named the security, cost, support, and exit conditions.",
      gate: "Go, revise, or hold",
      metric: "One bounded use case with written exit terms",
    },
    {
      name: "Veteran Ready Digital Launch",
      category: "Launch operations",
      challenge: "The website needed a credible release gate before the team shared it with employers and veterans.",
      response: "Converted readiness into owned checks for the offer, CTA, proof, privacy, legal, and contact path.",
      gate: "Controlled soft launch",
      metric: "6 release checks with named owners",
    },
    {
      name: "CR/VR Knowledge System",
      category: "Information operations",
      challenge: "Files could not serve as a reliable source of truth without one location, naming system, and owner model.",
      response: "Defined the decisions required for a safe inventory, migration, cutover, and verification process.",
      gate: "Migration cutover approval",
      metric: "One canonical system of record",
    },
  ],
};
